# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171025_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='section_description',
            new_name='description',
        ),
    ]
