# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171027_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
