# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20171031_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentuser',
            options={'verbose_name': 'доп. поле', 'verbose_name_plural': 'доп. поля'},
        ),
        migrations.AddField(
            model_name='commentuser',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='О себе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
    ]
