# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_remove_commentuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
